- name: setup database tier
  hosts: all
  become: yes
  roles:
    - {name: pretask, tags: base }

- name: setup frontends
  hosts: frontends
  become: yes
  roles:
    - { name: frontend, tags: front} 

- name: setup app
  hosts: apps
  become: yes
  roles:
    - { name: AppServer, tags: app } 

- name: setup DB
  hosts: appdbs
  become: yes
  roles:
    - { name: Dbserver, tags: db } 
