- name: in memory inventory
  hosts: workstation
  become: yes
  roles:
    - inmemory

- name: setup database tier
  hosts: all
  become: yes
  roles:
    - pretask

- name: setup frontends
  hosts: frontend
  become: yes
  roles:
    - frontend
- name: setup app
  hosts: apps
  become: yes
  roles:
    - AppServer
- name: setup DB
  hosts: appdbs
  become: yes
  roles:
    - Dbserver
